# -*- coding: utf-8 -*-
"""
Created on Wed Sep 10 22:17:18 2025

@author: BriceM
"""
import traceback 
from pathlib import Path


def dict_to_cfg(cfg_dict: dict, cfg_filename: str, cfg_filepath: str = "") -> bool:
    '''
    Converts a dictionary cfg_dict to a configuration file and saves it to cfg_filename in the
    directory cfg_filepath. If the filepath does not exist, it will create it.
    Returns whether it was successful or not.

    Parameters
    ----------
    cfg_dict : dict
        Dictionary containing all configuration parameters.
    cfg_filename : str
        Filename of the desired cfg file output (needs .cfg at the end), NO FILEPATH.
    cfg_filepath : str 
        Default is empty, constains as a str the desired final location of the config file.
    Returns
    -------
    success : bool
        True if no error occurs, False if exception is caught.

    '''
    try: 
        cfg_filepath = cfg_filepath + "\\" if cfg_filepath != "" else ""
        out_path = Path(cfg_filepath + cfg_filename)
        # Ensure parent directory exists (no-op if '.' or already present).
        out_path.parent.mkdir(parents=True, exist_ok=True)

        with out_path.open("w", encoding="utf-8", newline="\n") as f:
            for key, value in cfg_dict.items():
                # Cast to str to avoid TypeErrors on non-strings.
                f.write(f"{str(key)}= {str(value)}\n")

        print(f"SU2 configuration file '{out_path}' created successfully.")
        success = True
    except Exception as e:
        print("\nError Occured")
        print(e)
        traceback.print_exc()
        success = False
    finally:
        # handle other things if needed
        return success 
    
def txt_to_dict(filename: str, filepath: str = "") -> dict:
    """
    Reads a configuration file generated by dict_to_cfg() and converts it back
    into a Python dictionary.

    Parameters
    ----------
    filename : str
        Name of the cfg file (with extension).
    filepath : str
        Directory containing the file.

    Returns
    -------
    file_dict : dict
        Dictionary reconstructed from the config file.
    """

    filepath = filepath + "\\" if filepath != "" else ""
    in_path = Path(filepath + filename)

    file_dict = {}

    with in_path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()

            # Skip blank lines and comments
            if not line or line.startswith("#"):
                continue

            # Split only on first '='
            key, value = line.split("=", 1)
            key = key.strip()
            value = value.strip()

            # --- Type restoration ---
            if value.lower() == "none":
                value = None
            elif value.lower() == "true":
                value = True
            elif value.lower() == "false":
                value = False
            else:
                # Try numeric conversion
                try:
                    if "." in value or "e" in value.lower():
                        value = float(value)
                    else:
                        value = int(value)
                except ValueError:
                    # Leave as string
                    pass

            file_dict[key] = value

    return file_dict
       
        
   
if __name__ == "__main__":
    from base_config_params import cfg_params as params 
    filename = "test_config.cfg"
    filepath = "Configs"
    dict_to_cfg(params, filename, filepath)
    